version: '2'
services:
   
   ufsa:
      build:
         context: ./ufsa
      image: ufsa
      ports:
         - 111:111
         - 2049:2049
      environment: 
         - S3_URL=XXX
         - S3_USER=XXX
         - S3_PASS=XXX
         - S3_ENCRYPT=XXX
      container_name: ufsa
      privileged: true

